### ISSUE TITLE
Internal Model Error with Apache in Windows

### ISSUE THREAD

**Issue by jhramirez320** [jjmontesl/cubesviewer#89]
I configured the cubesviewer app and cubes server to run off an Apache web server and a sqlite database file. However, I get this internal model error when I try to drilldown into a view:

Traceback (most recent call last):\r
  File "C:\\Python\\344\\lib\\site-packages\\flask\\app.py", line 1639, in full_dispatch_request\r
    rv = self.dispatch_request()\r
  File "C:\\Python\\344\\lib\\site-packages\\flask\\app.py", line 1625, in dispatch_request\r
    return self.view_functions[rule.endpoint](**req.view_args)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\server\\decorators.py", line 64, in wrapper\r
    return f(*args, **kwargs)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\server\\blueprint.py", line 305, in cube_model\r
    response["features"] = workspace.cube_features(g.cube)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\workspace.py", line 646, in cube_features\r
    return self.browser(cube, identity).features()\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\workspace.py", line 634, in browser\r
    **options)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\ext.py", line 225, in __call__\r
    return self.create(_ext_name, *args, **kwargs)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\ext.py", line 244, in create\r
    return ext.create(*args, **kwargs)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\ext.py", line 166, in create\r
    return factory(*args, **kwargs)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\sql\\browser.py", line 185, in __init__\r
    tables=tables)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\sql\\query.py", line 370, in __init__\r
    self.fact_table = self.physical_table(fact)\r
  File "C:\\Python\\344\\lib\\site-packages\\cubes\\sql\\query.py", line 534, in physical_table\r
    raise NoSuchTableError(msg)\r
cubes.sql.query.NoSuchTableError: No such fact table 'fact_revenue'.\r

This a what my slicer.ini file looks like:

# Slicer OLAP server configuration

[workspace]
log_level: debug

[server]
host: localhost
port: 500
reload: yes
prettyprint: yes
allow_cors_origin: *
json_record_limit: 10000

[models]
path: C:/company/revenue/main_revenue.json

[store]
type: sql
url: sqlite:///name_of_database.sqlite
fact_prefix= fact_

This issue does not occur when I run the command slicer serve slicer.ini and the name of the table that the error states is missing is call fact_revenue. I have also attached a picture of the db .Please help me out. Thanks.

![2016-11-10_1012](https://cloud.githubusercontent.com/assets/22899538/20182107/aa6be3a2-a72e-11e6-8d5d-3559906fcca6.png)

**Comment by jhramirez320** [comment]
This issue was fixed by using a .db file
