### ISSUE TITLE
Quick Start guide non working under Windows

### ISSUE THREAD

**Issue by 62mkv** [jjmontesl/cubesviewer#98]
With Windows 10 x64, 

if you literally follow the instructions on the Quick Start guide, it all ends with 

```
2018-06-22 23:16:40,052 DEBUG Server authentication method: none
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python3\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\python3\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\kiril\downloads\cubes-examples\env\lib\site-packages\werkzeug\serving.py", line 774, in inner
    fd=fd)
  File "c:\users\kiril\downloads\cubes-examples\env\lib\site-packages\werkzeug\serving.py", line 663, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "c:\users\kiril\downloads\cubes-examples\env\lib\site-packages\werkzeug\serving.py", line 643, in __init__
    raise ValueError('Your platform does not support forking.')
ValueError: Your platform does not support forking.
```

if I remove option `processes: 6` from `webshop\slicer.ini` file, error goes away. I think it should be reflected in the guide

thanks!

**Comment by jjmontesl** [comment]
Thanks. I added this note to both the cubes-examples README and the quickstart guide.
